# Generated by Django 6.0.4 on 2026-04-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssubmission',
            name='bert_semantic_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newssubmission',
            name='gcn_propagation_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newssubmission',
            name='shares_analyzed',
            field=models.IntegerField(default=500, help_text='Optimized threshold: 300-500 shares for high-accuracy detection'),
        ),
        migrations.AddField(
            model_name='newssubmission',
            name='uncertainty_score',
            field=models.FloatField(default=0, help_text='Standard deviation/reliability of prediction'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newssubmission',
            name='confidence_score',
            field=models.FloatField(help_text='Mean probability from 50 MC Dropout passes'),
        ),
        migrations.AlterField(
            model_name='newssubmission',
            name='prediction',
            field=models.CharField(choices=[('REAL', 'Real'), ('FAKE', 'Fake'), ('UNCERTAIN', 'Uncertain')], max_length=15),
        ),
    ]
